# Arweave upload file
name: 'Arweave upload file'
description: 'Upload a file to the Arweave blockchain'
inputs:
  key_file_content:
    description: 'Arweave key file content'
    required: true
    default: false
  file_path:
    description: 'Path to the file to be uploaded'
    required: true
    default: false
  package:
    description: 'Package HTML dependencies into a single self-contained file'
    required: false
    default: false
  ipfs:
    description: 'Upload to IPFS as well (experimental)'
    required: false
    default: false
outputs:
  arweave_url:
    description: 'The Arweave URL your file will be available at once mined'
  ipfs_url:
    description: 'The IPFS URL your file will be available at once mined'
  cost:
    description: 'Transaction cost'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.key-file-content }}
    - ${{ inputs.file-path }}
    - ${{ inputs.package }}
    - ${{ inputs.ipfs }}
branding:
  icon: 'file-plus'  
  color: 'gray-dark'